site_name: K3S Cluster
repo_url: https://github.com/febus982/k3s-cluster
repo_name: febus982/k3s-cluster
nav:
  - Home: index.md
  - Network design: network.md
  - Preparation: preparation.md
  - Load balancers setup: load_balancers.md
  - K3S nodes setup: k3s_nodes.md

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/febus982/flux-k3s-cluster
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/federico-b-a0b78232/

plugins:
  - search
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(window.localStorage.getItem('/.__palette')).index == 1) ? 'dark' : 'neutral'

extra_javascript:
  - extra/refresh_on_toggle_dark_light.js
