---
- name: Create config directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory

- name: Copy K3S config file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/config.yaml.j2"
    dest: /etc/rancher/k3s/config.yaml

- name: Install K3S Master
  shell:
    cmd: "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=server sh -"
    creates: /etc/rancher/k3s/k3s.yaml

- name: Wait for K3S config
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml

- name: Fetch node-token
  ansible.builtin.fetch:
    src: /var/lib/rancher/k3s/server/node-token
    dest: "{{ playbook_dir }}/../../node-token"
    flat: yes
  become: true

#### External kubeconfig
- name: Copy kubeconfig file to tmp directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /tmp/kubeconfig
    remote_src: yes

- name: "Replace https://localhost:6443 by https://{{ lb_external_floating_ip }}:6443"
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ lb_external_floating_ip }}:6443
      --kubeconfig /tmp/kubeconfig
  changed_when: true

- name: Fetch kubeconfig
  ansible.builtin.fetch:
    src: /tmp/kubeconfig
    dest: "{{ playbook_dir }}/../../kubeconfig.yml"
    flat: yes

- name: Remove temp kubeconfig
  ansible.builtin.file:
    path: /tmp/kubeconfig
    state: absent
...
