---
- name: Add web service configuration file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/svc.hcl.j2"
    dest: /etc/consul.d/svc_{{ service_name }}.hcl
  become: yes

- name: Enable and restart consul
  ansible.builtin.systemd:
    name: consul
    state: restarted
    enabled: yes
  become: yes
...