---
- name: Apply RBAC
  command:
    cmd: kubectl apply -f https://kube-vip.io/manifests/rbac.yaml

# Note: Shouldn't ctr auto-pull the image? Without this the system throws an error
- name: Pull kube-vip image
  shell:
    cmd:
      ctr i pull
      ghcr.io/kube-vip/kube-vip:$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")
  become: yes

- name: Generate kube-vip manifests
  shell:
    cmd: >
      ctr run
      --rm --net-host
      ghcr.io/kube-vip/kube-vip:$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")
      vip /kube-vip
      manifest daemonset
      --interface eth0
      --address {{ control_plane_floating_ip }}
      --inCluster
      --taint
      --controlplane
      --enableLoadBalancer
      --services
      --arp
      --leaderElection > ./kube-vip.yaml
  become: yes

- name: Apply kube-vip manifests
  command:
    cmd: kubectl apply -f ./kube-vip.yaml

##### Cloud controller setup ######
- name: Copy ConfigMap
  ansible.builtin.template:
    src: "{{ role_path }}/templates/kube-vip-config.yml.j2"
    dest: ./kube-vip-config.yml
  when: not k3s_components.servicelb

- name: Copy cloud controller
  ansible.builtin.copy:
    src: "{{ role_path }}/files/kube-vip-cloud-controller.yml"
    dest: ./kube-vip-cloud-controller.yml
  when: not k3s_components.servicelb

# Add in fluxcd repository
- name: Apply ConfigMap
  command:
    cmd: kubectl apply -f ./kube-vip-config.yml
  when: not k3s_components.servicelb

- name: Apply cloud controller
  command:
    cmd: kubectl apply -f ./kube-vip-cloud-controller.yml
  when: not k3s_components.servicelb
