---
- hosts: k3s_cluster
  gather_facts: yes
  become: no
  roles:
    - role: k3s/prereq
    - role: apt_dependencies
    - role: reboot_and_reconnect
    - role: ntp
    - role: reboot_and_reconnect

- hosts: master
  gather_facts: yes
  become: no
  # We need to init the first master separately
  serial:
    - 1
    - "100%"
  roles:
    - role: k3s/master
      become: yes

- hosts: node
  gather_facts: yes
  become: no
  roles:
    - role: k3s/agent
      become: yes

# Find an appropriate host to run this :/
- hosts: master1
  gather_facts: yes
  become: no
  roles:
    - role: fluxcd
      when: flux.enabled
...
