---
# Find an appropriate host to run this :/
- hosts: master1
  gather_facts: no
  become: no
  vars:
    app: none
  roles:
    - role: coredns
      when: app in ('all', 'coredns') and not k3s_components.coredns
    - role: kube-vip
      when: app in ('all', 'kube-vip')
    - role: vertical_autoscaler
      when: app in ('all', 'vertical_autoscaler') and vertical_autoscaler.enabled
    - role: fluxcd
      when: app in ('all', 'fluxcd') and fluxcd.enabled
...
