---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
  become: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
  become: yes

- name: Verify IPv4 forwarding is enabled
  command: cat /proc/sys/net/ipv4/ip_forward
  register: ipv4_forward_command
  failed_when: ipv4_forward_command.stdout != '1'

- name: Verify IPv6 forwarding is enabled
  command: cat /proc/sys/net/ipv6/conf/all/forwarding
  register: ipv6_forward_command
  failed_when: ipv6_forward_command.stdout != '1'

- name: Enable IPv4 arp filtering
  sysctl:
    name: net.ipv4.conf.all.arp_filter
    value: "1"
    state: present
    reload: yes
  become: yes

- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present
    update_cache: yes
  become: yes

- name: Add iptables rules
  ansible.builtin.template:
    src: "{{ role_path }}/templates/rules.v4.j2"
    dest: /etc/iptables/rules.v4
  become: yes

- name: Load iptables rules
  shell: "iptables-restore < /etc/iptables/rules.v4"
  become: yes
...
